declare module 'react-navigation-redux-helpers';
declare module '@expo/vector-icons';
declare module 'react-native-svg-charts'
declare module 'react-native-pie-chart'
declare module 'react-native-table-component'
declare module 'd3-shape'
declare module 'react-native-d3multiline-chart'
declare module 'd3-scale'
declare module 'expo'
declare module 'react-native-svg'
