export const NAME = 'reportDetail'
export const GET_DETAIL_REPORT = 'GET_DETAIL_REPORT'
export const GET_DETAIL_REPORT_SUCCESS = 'GET_DETAIL_REPORT_SUCCESS'
export const GET_DETAIL_REPORT_CACHE = 'GET_DETAIL_REPORT_CACHE'
